services:
  authelia:
    image: authelia/authelia:4
    container_name: authelia
    restart: unless-stopped

    networks:
      - proxy

    environment:
      TZ: America/Phoenix

    volumes:
      - ../config:/config:Z
      - ../data:/data:Z

networks:
  proxy:
    external: true
