http:
  routers:
    authelia:
      rule: Host(`auth.az-lab.dev`)
      entryPoints:
        - websecure
      service: authelia
      tls:
        certResolver: le

  services:
    authelia:
      loadBalancer:
        servers:
          - url: http://authelia:9091
        passHostHeader: true

  middlewares:
    authelia-auth:
      forwardAuth:
        address: http://authelia:9091/api/authz/forward-auth
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
