server:
  address: 'tcp://:9091'

log:
  level: info

theme: dark

totp:
  issuer: az-lab.dev

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id

access_control:
  default_policy: deny
  rules:
    - domain: auth.az-lab.dev
      policy: bypass

    - domain: grafana.az-lab.dev
      policy: one_factor

    - domain: games.az-lab.dev
      policy: one_factor

    - domain: traefik.az-lab.dev
      policy: one_factor

session:
  secret: REPLACE_WITH_RANDOM_SECRET_1
  cookies:
    - name: authelia_session
      domain: az-lab.dev
      authelia_url: https://auth.az-lab.dev
      expiration: 12h
      inactivity: 1h

storage:
  encryption_key: REPLACE_WITH_RANDOM_SECRET_2
  local:
    path: /data/db.sqlite3

notifier:
  smtp:
    address: smtp://smtp-relay.brevo.com:587
    username: REPLACE_WITH_BREVO_LOGIN_EMAIL
    password: REPLACE_WITH_BREVO_API_KEY
    sender: authelia@az-lab.dev
    subject: "[Authelia] {title}"
